services:
  - type: web
    name: rk-raja-xwd-server
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT

    envVars:
      - key: FB_ACCESS_TOKEN
        sync: false
